& "$PSScriptRoot\..\gitmodules\mod-installer\build_all.ps1" `
  -Version "2.0.0" `
  -PreReleaseVersion "beta.1" `
  -OutputFilePrefix "SMOD_Tactical_Delta_5.56" `
  -ModName "SMOD: Tactical Delta 5.56" `
  -ModFolder "smodtactical556" `
  -ModFilesPath "$PSScriptRoot\..\game" `
  -ModBaseFilesUrl "https://github.com/HL2-Mods-Legacy-Project/hl2-legacy-registry/releases/download/smod-tactical/smodtactical-5.56-full+texturefix.zip" `
  -ModBaseFilesUrlHash "37eb3c850981a6f1dece71dfdbeec5e56c5ed8d1ef564a43e997e22052e036e9" `
  -ModReadmePath "Tactical-Readme.txt" `
  -PublishPath "$PSScriptRoot\..\artifacts\publish"
